import "./globals.css";

export const metadata = {
    title: "Learnosity Basic React",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
                    {children}
                </div>
            </body>
        </html>
    );
}
